/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nccloud.VM2;

import static nccloud.VM1.vm1.dpath1;
import static nccloud.VM1.vm1.port;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class vm2 extends javax.swing.JFrame {

    public static int port[] = {100, 200, 300};
    public static String dpath1 = "D:/VM2";
    Random rn = new Random();
    String path1;
    int lenpath1;
    String f1[] = new String[10];
    String err, perr;
    String fname1, fname2;
    ArrayList<String> fname = new ArrayList<String>();

    /**
     *
     * /**
     * Creates new form vm2
     */
    public vm2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 471));
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(153, 153, 255));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Virtual Machine 2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 705, 71);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Files", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel2.setLayout(null);

        jButton1.setText("Receive");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(56, 30, 200, 32);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 260, 190);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 30, 310, 300);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Regenerate", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel3.setLayout(null);

        jButton2.setText("Virtual Machine1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(40, 55, 200, 72);

        jButton3.setText("Virtual Machine3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(40, 180, 200, 80);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(370, 30, 270, 300);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 70, 700, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            try {
                int p = rn.nextInt(port.length);
                System.out.println(p);
                Socket s = new Socket("localhost", port[p]);
                BufferedReader br = new BufferedReader(new InputStreamReader(s.getInputStream()));
                path1 = br.readLine();
                lenpath1 = Integer.parseInt(br.readLine());
                f1[0] = br.readLine();
                f1[1] = br.readLine();
                jTextArea1.append("Original Files" + "\n");
                jTextArea1.append("======================================================================" + "\n");
                jTextArea1.append("Filename:" + "\t" + f1[0] + "\n" + "Filename:" + "\t" + f1[1] + "\n");
                jTextArea1.append("======================================================================" + "\n");
                br.close();
                s.close();

            } catch (Exception e1) {
                err = e1.getMessage();
                perr = err;
                JOptionPane.showMessageDialog(this, "Network unavailable");
            }
            if (perr.equals(err)) {
                File f = new File(dpath1);
                File fs[] = f.listFiles();
                for (int i = 0; i < fs.length; i++) {
                    fname.add(fs[i].getName());
                    fs[i].delete();
                }
            }
            System.out.println(fname);
        } catch (Exception e) {
            System.out.println("Exception : " + e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            System.out.println(fname);
            ServerSocket ss = new ServerSocket(500);
            Socket sock = ss.accept();
            PrintStream ps = new PrintStream(sock.getOutputStream());
            BufferedReader br = new BufferedReader(new InputStreamReader(sock.getInputStream()));

            int n = fname.size();
            ps.println(Integer.toString(n));

            for (int i = 0; i < n; i++) {
                ps.println(fname.get(i));
            }
            BufferedInputStream bis = new BufferedInputStream(sock.getInputStream());
            DataInputStream dis = new DataInputStream(bis);
            String b = br.readLine();
            long fileLength = dis.readLong();
            File fj = new File(dpath1 + "/" + b);
            FileOutputStream fos = new FileOutputStream(fj);
            BufferedOutputStream bos = new BufferedOutputStream(fos);

            for (int j = 0; j < fileLength; j++) {
                bos.write(bis.read());
            }

            bos.close();

            JOptionPane.showMessageDialog(this, b+" uploaded successfully");

            br.close();
            ps.close();
            sock.close();
            ss.close();

        } catch (Exception e) {
            System.out.println("Exception : " + e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            System.out.println(fname);
            ServerSocket ss = new ServerSocket(505);
            Socket sock = ss.accept();
            PrintStream ps = new PrintStream(sock.getOutputStream());
            BufferedReader br = new BufferedReader(new InputStreamReader(sock.getInputStream()));

            int n = fname.size();
            ps.println(Integer.toString(n));

            for (int i = 0; i < n; i++) {
                ps.println(fname.get(i));
            }
            BufferedInputStream bis = new BufferedInputStream(sock.getInputStream());
            DataInputStream dis = new DataInputStream(bis);
            String b = br.readLine();
            long fileLength = dis.readLong();
            File fj = new File(dpath1 + "/" + b);
            FileOutputStream fos = new FileOutputStream(fj);
            BufferedOutputStream bos = new BufferedOutputStream(fos);

            for (int j = 0; j < fileLength; j++) {
                bos.write(bis.read());
            }

            bos.close();

            JOptionPane.showMessageDialog(this, b+" uploaded successfully");

            jTextArea1.append("Origianl Files:" + "\n");
            jTextArea1.append("======================================================================" + "\n");
            File f = new File(dpath1);
            File fs[] = f.listFiles();
            for (int i = 0; i < fs.length; i++) {
                jTextArea1.append("Filename:" + "\t" + fs[i].getName() + "\n");
            }
            jTextArea1.append("======================================================================" + "\n");
            br.close();
            ps.close();
            sock.close();
            ss.close();

        } catch (Exception e) {
            System.out.println("Exception : " + e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vm2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
